version: 2

sources:
  - name: raw
    schema: gz_raw_data
    tables:
      - name: adwords
        identifier: raw_gz_adwords
        description: Adwords advertising campaign raw data

      - name: bing
        identifier: raw_gz_bing
        description: Bing advertising campaign raw data

      - name: criteo
        identifier: raw_gz_criteo
        description: Criteo advertising campaign raw data

      - name: facebook
        identifier: raw_gz_facebook
        description: Facebook advertising campaign raw data

models:
    - name: stg_raw__adwords
      description: Cleaned staging model for Adwords campaign data
      columns:
          - name: date_date
            description: date of the campaign
            tests:
                - not_null

          - name: paid_source
            description: advertising sources
            tests:
                - not_null

          - name: campaign_key
            description: campaign identifier
            tests:
                - not_null
                          
          - name: camPGN_name
            description: campaign name

          - name: ads_cost
            description: Advertising cost as float64
            tests:
                - not_null

          - name: impression
            description: number of ad impression

          - name: click
            description: number of ad clicks     
                   
            
    - name: stg_raw__bing
      description: Cleaned staging model for Bing campaign data
      columns:
          - name: date_date
            tests:
              - not_null

          - name: paid_source
            tests:
              - not_null

          - name: campaign_key
            tests:
              - not_null

          - name: camPGN_name

          - name: ads_cost
            tests:
              - not_null

          - name: ads_impression

          - name: ads_clicks
 
    - name: stg_raw__criteo
      description: Cleaned staging model for Criteo campaign data
      columns:
          - name: date_date
            tests:
              - not_null

          - name: paid_source
            tests:
              - not_null

          - name: campaign_key
            tests:
              - not_null

          - name: campaign_name

          - name: ads_cost
            tests:
              - not_null

          - name: ads_impression

          - name: ads_clicks

    - name: stg_raw__facebook
      description: Cleaned staging model for Facebook campaign data
      columns:
          - name: date_date
            tests:
              - not_null

          - name: paid_source
            tests:
              - not_null

          - name: campaign_key
            tests:
              - not_null

          - name: campaign_name

          - name: ads_cost
            tests:
              - not_null

          - name: ads_impression

          - name: ads_clicks